//Default Sentinel ZIA parser
_ASim_WebSession_ZscalerZIAV03()
//Filter on possible phishing links
| where urlclass == "Advanced Security Risk"
//Only output unique entries within the last hour
| distinct User, RequestURL, UrlCategory, DeviceEventClassID, EventOriginalResultDetails, ThreatName ,RuleName, NetworkApplicationProtocol, ThreatRiskLevel, bin(TimeGenerated, 1h)
//Only generate an alert if 5 or more users clicked on a possible phishing link
| summarize Clicks = make_list(User), dcount(User) by RequestURL, UrlCategory, DeviceEventClassID, EventOriginalResultDetails, ThreatName ,RuleName, NetworkApplicationProtocol, ThreatRiskLevel, bin(TimeGenerated, 1h)
| project TimeGenerated, dcount_User, RequestURL, NetworkApplicationProtocol, DeviceEventClassID, EventOriginalResultDetails, ThreatRiskLevel, UrlCategory, ThreatName, RuleName, Clicks
| where dcount_User >= 5
